title: Autofac Illustrated
copyright: Copyright (c) 2011 Suhair, All Rights Reserved
authors:
  - Suhair 
subject: Ruby on Rails
keywords: rails, ruby, framework, development
theme: eiffel
base_url: http://example.com